### ISSUE TITLE
Community store won't update list

### ISSUE THREAD

**Issue by Spidy123222** [SideStore/Community-Source#1]
The list to update the store automatically doesn't work after attempt of doing redirecting code.

**Comment by JoeMatt** [comment]
aight, I have to trace what happens after the redirect.

It could be something else with the URL changes though.

Give me a day, exhausted today.

**Comment by Spidy123222** [comment]
> aight, I have to trace what happens after the redirect.
> 
> It could be something else with the URL changes though.
> 
> Give me a day, exhausted today.

I also forgot that I didn't get redirect to fully work. I'm pretty sure for updating code written in Python is that the extra lines in the Json is causing that issue.

**Comment by noah978** [comment]
In case you forgot our conversation in the discord, the reason the sources are no longer updating is because my AltSourceParser code uses Pythons standard json library to read the files. Since you don't trim the markdown headers before loading the file, it is technically invalid json. For now, the easy solution is to simply trim the header before using it, and then add the headers after the updates are complete.

Also, I will note that I am currently in the process of refactoring the code and creating a PyPI package in this repository (https://github.com/noah978/AltSourceParser) which should make the code cleaner and easier for you and others to use to auto-update your source.

**Comment by noah978** [comment]
Check out #2 for my changes to fix all the issues and get the update script and workflow up-to-date

**Comment by Spidy123222** [comment]
Instead of using markdown redirect we could use cloudflare since that's been added recently and this can apply to apps.sidestore.io also.

**Comment by lonkelle** [comment]
@Spidy123222 You mentioned this is still the case and is likely related to https://github.com/SideStore/SideStore/issues/103 - so I'll mark that issue as a Soft Launch milestone.
