### ISSUE TITLE
QuarkSource QuantumSource

### ISSUE THREAD

**Issue by upintheairsheep** [SideStore/Community-Source#36]
Add the quantum source to sidestore community source.
https://github.com/QuarkSources/quarksources.github.io/blob/main/quantumsource.json

**Comment by nythepegasus** [comment]
We had a big discussion about this as a team the other day, and we will not be adding sources with tweaked apps that skirt around paid features. We still have plans and ideas in the future to allow for tweaked apps to exist, just nothing concrete right now which is why I will close this and will add this as a TODO elsewhere.

**Comment by upintheairsheep** [comment]
It does not have any of it. It's just emulators. 


Sent from my Apple Watch
